[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = """
    default-src 'self';
    script-src 'self' https://www.googletagmanager.com https://unpkg.com;
    style-src 'self';
    img-src 'self' data:;
    font-src 'self';
    connect-src 'self' https://www.google-analytics.com;
    object-src 'none';
    frame-ancestors 'self';
  """
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Permissions-Policy = "geolocation=(), microphone=(), camera=()"
